### ISSUE TITLE
fix the bug on the screel post[instead of displaying "%time ago" display "in %time' "] e.g in 5 hours, in 24 hours, in 10 minutes etc

### ISSUE THREAD

**Issue by FotieMConstant** [FotieMConstant/screel#18]

**Comment by Samsonroyal** [comment]
How do I recreate this bug on my machine to dig in? the badge on screel post right now displays "Fades in 23 hours", was this fixed? @fotieMConstant

**Comment by FotieMConstant** [comment]
hey @Samsonroyal this bug was already fixed! we probably just forgot to close this issue...

**Comment by Samsonroyal** [comment]
good to hear @FotieMConstant
